### ISSUE TITLE
如何调用 BMap 其他服务

### ISSUE THREAD

**Issue by fuchao2012** [gengen1988/ng-baidu-map#1]
代码中会用到基于 BMAP 的服务，例如下面代码

```
var localcity = new BMap.LocalCity();
      localcity.get(function(r){
      this.$log.debug(r);
    });
```

会报一个 BMap 未定义的错， BMap 有注入到 bootstrap 中吗？

**Comment by gengen1988** [comment]
Hi, 

你可以注入 `baiduMapApi`。这是个 Promise，在 Then 里拿到 BMap。例如：

``` js
// 定义自己的服务
yourModule.factory('BaiduMapService', function($q, baiduMapApi) {
  return {
    getLocalCity: function() {
      return baiduMapApi.then(function(BMap) {
        var localcity = new BMap.LocalCity();
        return $q(function(resolve, reject) {
          localcity.get(function(r) {
            resolve(r);
          });
        });
      });
    }
  };
});

// 使用自己的服务
yourModule.controller('TestController', function(BaiduMapService) {
  var self = this;
  BaiduMapService.getLocalCity().then(function(r) {
    self.r = r;
  });
});
```

**Comment by dandingol03** [comment]
您好,我在controller层直接调baiduMapApi返回的bmap进行渲染，但是浏览器调试时有效，手机却出不来
以下代码
controller:
  BaiduMapService.getBMap(function(BMap){
            var map = new BMap.Map("container");          // 创建地图实例
            var point = new BMap.Point(116.404, 39.915);  // 创建点坐标
            map.centerAndZoom(point, 15);
        });
html:
<ion-view name="life_insurance-view" hide-back-button="false">
    <ion-nav-bar>
        <ion-nav-buttons side="primary">
        </ion-nav-buttons>
        <ion-nav-title>
            <span> map panel</span>
        </ion-nav-title>
    </ion-nav-bar>
    <ion-content>

        <div id="container" style="width:800px;height:400px"></div>
    </ion-content>
</ion-view>

**Comment by dandingol03** [comment]
#### 您好
我直接通过baiduMapApi返回的bmap进行渲染,浏览器可以，手机无效，ak对应android
以下代码
controller:
```
        BaiduMapService.getBMap(function(BMap){
            var map = new BMap.Map("container");          // 创建地图实例
            var point = new BMap.Point(116.404, 39.915);  // 创建点坐标
            map.centerAndZoom(point, 15);
        });
```
view:
```
<ion-content>  
<div id="container" style="width:800px;height:400px"></div>
</ion-content>
```
